import React, { Component } from 'react';
import {
    StyleSheet,
    Platform
} from 'react-native';

import { deviceWidth, deviceHeight, scaleSize } from '../tools/adaptation';


const CommonStyles = StyleSheet.create({
    containerFull:{
        backgroundColor:'#f0f3f8',
        height:'100%'
    },
    containerHeight90:{
        height:Platform.OS == 'ios' ? deviceHeight-scaleSize(120) : deviceHeight-scaleSize(120),
        backgroundColor:'#f0f3f8'
    },
    containerHeight100:{
        height:Platform.OS == 'ios' ? deviceHeight-scaleSize(100) : deviceHeight-scaleSize(100),
        backgroundColor:'#fff'
    },
    containerHeight180:{
        height:Platform.OS == 'ios' ? deviceHeight-scaleSize(220) : deviceHeight-scaleSize(220),
        backgroundColor:'#fff'
    },
    containerHeight360:{
        height:Platform.OS == 'ios' ? deviceHeight-scaleSize(360) : deviceHeight-scaleSize(360),
        backgroundColor:'#fff'
    },
    containerHeight:{
        height: deviceHeight,
        backgroundColor:'#fff',
    },
    marT10:{
        marginTop:scaleSize(10),
    },
    marT20:{
        marginTop:scaleSize(20),
    },
    marl10:{
        marginLeft:scaleSize(10),
    },
    marB10:{
        marginBottom:scaleSize(10),
    },
    marB20:{
        marginBottom:scaleSize(20),
    },
    marR10:{
        marginRight:scaleSize(10),
    },
    padL10:{
        paddingLeft:scaleSize(10),
    },
    padR10:{
        paddingRight:scaleSize(10),
    },
    padR20:{
        paddingRight:scaleSize(20),
    },
    padT20:{
        paddingTop:scaleSize(20),
    },
    padB20:{
        paddingBottom:scaleSize(20),
    },
    padT30:{
        paddingTop:scaleSize(30),
    },
    pad10:{
        padding:scaleSize(10),
    },
    pad20:{
        padding:scaleSize(20),
    },
    pt10pl20:{
        paddingLeft:scaleSize(20),
        paddingRight:scaleSize(20),
        paddingTop:scaleSize(15),
        paddingBottom:scaleSize(15)
    },
    marR5:{
        marginRight:scaleSize(5),
    },
    flexRow:{
        flexDirection:'row'
    },
    bgBlue:{
        backgroundColor:'#498CC0'
    },
    bgWhite:{
        backgroundColor:'#ffffff'
    },
    bgf3:{
        backgroundColor:'#f3f3f3'
    },
    bgf5:{
        backgroundColor:'#f5f5f5'
    },
    disabled:{
        backgroundColor:'#CCCCCC'
    },
    colorBlack:{
        color:'#000'
    },
    colorWhite:{
        color:'#ffffff'
    },
    colorBlue:{
        color:'#498CC0'
    },
    color666:{
        color:'#666666'
    },
    color999:{
        color:'#999999'
    },
    color333:{
        color:'#333'
    },
    color444:{
        color:'#888',
    },
    colorGray:{
        color:'#CCCCCC'
    },
    colorB1:{
        color:'#b1b1b1'
    },
    color009:{
        color:'#009900'
    },
    colorRed:{
        color:'#f00'
    },
    colorGreen:{
        color:'#488CBF'
    },
    fs16:{
        fontSize:scaleSize(16)
    },
    fs18:{
        fontSize:scaleSize(18)
    },
    fs20:{
        fontSize:scaleSize(20)
    },
    fs22:{
        fontSize:scaleSize(22)
    },
    fs24:{
        fontSize:scaleSize(24)
    },
    fs26:{
        fontSize:scaleSize(26)
    },
    fs28:{
        fontSize:scaleSize(28)
    },
    fs30:{
        fontSize:scaleSize(30)
    },
    fs40:{
        fontSize:scaleSize(40)
    },
    fs42:{
        fontSize:scaleSize(42)
    },
    lineHeight30:{
        lineHeight:scaleSize(30)
    },
    lineHeight48:{
        // Platform.OS ?
        // lineHeight: scaleSize(48),
        textAlignVertical:'center'
    },
    borderTopBottom:{
        borderTopWidth:scaleSize(1),
        borderBottomWidth:scaleSize(1),
        borderColor:'#eee',
    },
    borderBottom:{
        borderBottomWidth:scaleSize(1),
        borderColor:'#eee',
    },
    borderTop:{
        borderTopWidth:scaleSize(1),
        borderColor:'#eee',
    },
    border:{
        borderWidth:scaleSize(1),
        borderColor:'#eee',
    },
    loginBox:{
        paddingLeft:scaleSize(80),
        paddingRight:scaleSize(80),
        paddingTop:scaleSize(95),
    },

    contentInput:{
        width:'100%',
        height:scaleSize(60),
        backgroundColor:'#fff',
        justifyContent:'center',
        alignItems:'center',
        marginBottom:scaleSize(20),
        borderColor:'#ccc',
        borderWidth:scaleSize(1),
        borderRadius:scaleSize(5),
        paddingLeft:scaleSize(52),
        flexDirection:'row'
    },
    contentInputNoLeft:{
        width:'100%',
        height:scaleSize(60),
        backgroundColor:'#fff',
        justifyContent:'center',
        alignItems:'center',
        borderColor:'#ccc',
        borderWidth:scaleSize(1),
        borderRadius:scaleSize(5),
        paddingLeft:scaleSize(10),
        flexDirection:'row',
    },

    contentInputNoLeftBorderBottom:{
        width:'100%',
        height:scaleSize(60),
        backgroundColor:'#fff',
        justifyContent:'center',
        alignItems:'center',
        borderBottomWidth:scaleSize(1),
        borderColor:'#ccc',
        paddingLeft:scaleSize(10),
    },
    Input:{
        width:'100%',
        height:'100%',
        padding: 0,
        fontSize:scaleSize(22),
        color:'#666',
        // lineHeight:scaleSize(40)
    },
    posRe:{
        position:'relative',
    },
    posAb:{
        position:'absolute',
    },
    scan:{
        width:scaleSize(32),
        height:scaleSize(32),
        // top:scaleSize(12),
        // right:scaleSize(15),
    },
    phone:{
        width:scaleSize(27),
        height:scaleSize(40),
        top:scaleSize(8),
        left:scaleSize(15),
    },
    password:{
        width:scaleSize(29),
        height:scaleSize(36),
        top:scaleSize(10),
        left:scaleSize(15),
    },
    phonecode:{
        width:scaleSize(40),
        height:scaleSize(40),
        top:scaleSize(7),
        left:scaleSize(8),
    },
    arrowdown:{
        width:scaleSize(22),
        height:scaleSize(11),
        top:scaleSize(22),
        right:scaleSize(15),
    },
    rili:{
        width:scaleSize(32),
        height:scaleSize(29),
        top:scaleSize(13),
        right:scaleSize(15),
    },
    file:{
        width:scaleSize(31),
        height:scaleSize(37),
        top:scaleSize(8),
        right:scaleSize(15),
    },
    dizhi:{
        width:scaleSize(20),
        height:scaleSize(25),
        top:scaleSize(15),
        right:scaleSize(15),
    },
    dizhi:{
        width:scaleSize(20),
        height:scaleSize(25),
        top:scaleSize(12),
        right:scaleSize(15),
    },
    btnContent:{
        alignItems:'center',
        marginTop:scaleSize(20),
    },
    sub:{
        width:'100%',
        justifyContent:'center',
        alignItems:'center',
        height:scaleSize(90),
        backgroundColor:'#dd544d',
        borderRadius:scaleSize(10),
        marginBottom:scaleSize(40),
    },
    subBtn:{
        fontSize:scaleSize(36),
        color:'#ffffff'
    },
    loginBoxFor:{
        flexDirection:'row'
    },
    loginBoxForList:{
        flex:1
    },
    loginBoxForListRight:{
        alignItems:'flex-end'
    },
    forget:{

    },
    forgetTxt:{
        fontSize:scaleSize(20),
        color:'#488CBF'
    },
    loginTop:{
        height:Platform.OS == 'ios' ? scaleSize(430) : scaleSize(430),
    },
    loginTopContent:{
        paddingTop:Platform.OS == 'ios' ? scaleSize(90) : scaleSize(50),
        zIndex:2,
        alignItems:'center',
    },
    loginTopBg:{
        width:'100%',
        height:scaleSize(94),
        position:'absolute',
        bottom:0,
        left:0
    },
    loginTopImg:{
        width:scaleSize(300),
        height:scaleSize(200),
    },
    btnContent:{
        paddingTop:scaleSize(30),
    },
    IndexTitleContent:{
        height:Platform.OS == 'ios' ? scaleSize(120) : scaleSize(80),
        paddingTop:Platform.OS == 'ios' ? scaleSize(40) : scaleSize(0),
        paddingLeft:scaleSize(20),
        paddingRight:scaleSize(20),
        alignItems:'center',
    },
    IndexTitleLeftImg:{
        width:scaleSize(163),
        height:scaleSize(54),
    },
    loginBoxForListRightList:{
        paddingLeft:scaleSize(30),
        alignSelf:'flex-end'
    },
    smallCode:{
        width:scaleSize(38),
        height:scaleSize(38),
    },
    doubleChange:{
        width:scaleSize(34),
        height:scaleSize(32),
    },
    banner:{
        width:'100%',
        height:scaleSize(270),
    },
    IndexRoleContent:{
        height:scaleSize(110),
        paddingLeft:scaleSize(20),
        paddingRight:scaleSize(20),
        justifyContent:'center',
        backgroundColor:'#fff',
        marginBottom:scaleSize(15),
    },
    roleTag:{
        width:scaleSize(86),
        height:scaleSize(27),
        borderRadius:scaleSize(5),
        justifyContent:'center',
        alignItems:'center',
        marginLeft:scaleSize(10),
    },
    emptyContent:{
        height:scaleSize(500),
        justifyContent:'center',
        alignItems:'center'
    },
    empty:{
        fontSize:scaleSize(24),
        color:'#999'
    },
    infoContent:{
        height:scaleSize(70),
        paddingLeft:scaleSize(20),
        paddingRight:scaleSize(20),
        justifyContent:'flex-start'
    },
    paddingLR0:{
        paddingLeft:0,
        paddingRight:0,
    },
    codeRight:{
        position:'absolute',
        top:scaleSize(20),
        right:0,
    },
    codeImg:{
        width:scaleSize(30),
        height:scaleSize(30),
    },
    rightArr:{
        width:scaleSize(12),
        height:scaleSize(20),
    },
    radioscontent:{
        height:scaleSize(60),
        alignItems:'center',
    },
    flex1:{
        flex:1
    },
    infoView:{
        width:'100%',
        height:'100%',
        justifyContent:'flex-start',
        alignItems:'center',
        flexDirection:'row'
    },
    location:{
        width:scaleSize(14),
        height:scaleSize(17),
    },
    dirImg:{
        width:scaleSize(24),
        height:scaleSize(12),
    },
    rotate180:{
        transform:[{ rotate: '180deg' }]
    },
    rotate90:{
        transform:[{ rotate: '90deg' }]
    },
    textarea:{
        height:scaleSize(150),
        width:'100%',
        backgroundColor:'#fff',
        // justifyContent:'center',
        // alignItems:'center',
        borderColor:'#ccc',
        borderWidth:scaleSize(1),
        borderRadius:scaleSize(5),
        padding:scaleSize(10),
    },
    editTwoLeft:{
        paddingRight:scaleSize(5),
    },
    editTwoRight:{
        paddingLeft:scaleSize(5),
    },
    radios:{
        width:scaleSize(22),
        height:scaleSize(22),
    },
    checkBox:{
        width:scaleSize(30),
        height:scaleSize(30),
    },
    dataImgRight:{
        width:scaleSize(8),
        height:scaleSize(16),
    },
    TableBodyItemContent:{
        flexDirection:'row',
        justifyContent:'center',
        alignItems:'center'
    },
    personRightImgContent:{
        width:scaleSize(200),
        height:scaleSize(230),
        backgroundColor:'#fff',
        position:'absolute',
        top:0,
        right:0,
        justifyContent:'center',
        alignItems:'center',
        padding:scaleSize(20),
        zIndex:1
    },
    personRightImg:{
        width:'100%',
        height:'100%',
    },
    resContent:{
        paddingLeft:scaleSize(20),
        paddingRight:scaleSize(20),
    },
    resstepImgContent:{
        padding:scaleSize(20),

    },
    resstepImg:{
        width:'100%',
        height:scaleSize(80),
    },
    phoneCodeGet:{
        width:scaleSize(150),
        position:'absolute',
        top:scaleSize(-1),
        right:scaleSize(-1)
    },
    scanContent:{
        position:'absolute',
        top:scaleSize(0),
        right:scaleSize(0),
        width:scaleSize(60),
        height:scaleSize(58),
        justifyContent:'center',
        alignItems:'center'
    },
    ImgBox:{

    },
    picImg:{
        width:'100%',
        // height:,
        marginBottom:scaleSize(8)
    },
    picView:{
        paddingRight:scaleSize(10),
        paddingBottom:scaleSize(10),
        width:'33.33%'
        // borderWidth:scaleSize(1),
        // borderColor:'#eee'
    },
    close2Content1:{
        right:0,
    },
    close2Content:{
        width:scaleSize(30),
        height:scaleSize(30),
        position:'absolute',
        top:scaleSize(-10),
        right:scaleSize(10),
    },
    starImg:{
        width:scaleSize(40),
        height:scaleSize(40),
    },
    cancelbox:{
        minHeight:scaleSize(60),
        paddingLeft:scaleSize(10),
        justifyContent:'center',
        // alignItems:'center'
    },
    right0:{
        right:0
    },
    menucontent:{
        width:scaleSize(50),
        height:scaleSize(50),
        justifyContent:'center',
        alignItems:'flex-end'
    },
    emptyContentImg:{
        width:scaleSize(150),
        height:scaleSize(189)
    },
    addarealist:{
        width:'19%',
    },
    height2:{
        height:deviceWidth*0.65/3-scaleSize(15)
    },
    footerTip:{
        paddingTop:scaleSize(20),
        paddingBottom:scaleSize(30),
        justifyContent:'center',
        alignItems:'center'
    },
    logininput:{
        minHeight:scaleSize(60),
        height:scaleSize(60),
        width:'100%',
        justifyContent:'center',
    },
    textcenter:{
        textAlignVertical:'center'
    },
    bottombtnContent:{
        padding:scaleSize(20),
        paddingLeft:scaleSize(10),
        paddingRight:scaleSize(10),
        position:'absolute',
        bottom:0,
        left:0,
        right:0,
        zIndex:2,
        backgroundColor:'#eee',
        flexDirection:'row'
    },
    bottombtnContentlist:{
        flex:1,
        paddingLeft:scaleSize(10),
        paddingRight:scaleSize(10),
        justifyContent:'center',
        alignItems:'center'
    },
})
export default CommonStyles;